import './globals.css'
import { Noto_Sans_JP } from 'next/font/google'
import Link from 'next/link'
import React from 'react'

import type { Metadata } from 'next'

const noto = Noto_Sans_JP({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='box-border h-full'>
            <body className={`h-full ${noto.className}`}>
                <div className='md:mx-30 mx-5 flex h-full flex-col sm:mx-20 lg:mx-60'>
                    <header className='box-border py-10'>
                        <h1 className='text-3xl'>
                            <Link href='/'>ブログ</Link>
                        </h1>
                    </header>

                    <div className='flex-1'>{children}</div>

                    <footer className='py-3'>
                        <small>© 2023 </small>
                    </footer>
                </div>
            </body>
        </html>
    )
}
